package pm.bank.acct.bean;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table acct_info
 */
public class AcctInfo {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_info.acct_no
     *
     * @mbg.generated
     */
    private String acctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_info.acct_name
     *
     * @mbg.generated
     */
    private String acctName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_info.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_info.acct_yesterday_balance
     *
     * @mbg.generated
     */
    private BigDecimal acctYesterdayBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_info.acct_today_balance
     *
     * @mbg.generated
     */
    private BigDecimal acctTodayBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_info.data_create_user
     *
     * @mbg.generated
     */
    private String dataCreateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_info.data_create_time
     *
     * @mbg.generated
     */
    private String dataCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_info.data_update_user
     *
     * @mbg.generated
     */
    private String dataUpdateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_info.data_update_time
     *
     * @mbg.generated
     */
    private String dataUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_info.id
     *
     * @return the value of acct_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_info.id
     *
     * @param id the value for acct_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_info.acct_no
     *
     * @return the value of acct_info.acct_no
     *
     * @mbg.generated
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_info.acct_no
     *
     * @param acctNo the value for acct_info.acct_no
     *
     * @mbg.generated
     */
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo == null ? null : acctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_info.acct_name
     *
     * @return the value of acct_info.acct_name
     *
     * @mbg.generated
     */
    public String getAcctName() {
        return acctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_info.acct_name
     *
     * @param acctName the value for acct_info.acct_name
     *
     * @mbg.generated
     */
    public void setAcctName(String acctName) {
        this.acctName = acctName == null ? null : acctName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_info.user_id
     *
     * @return the value of acct_info.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_info.user_id
     *
     * @param userId the value for acct_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_info.acct_yesterday_balance
     *
     * @return the value of acct_info.acct_yesterday_balance
     *
     * @mbg.generated
     */
    public BigDecimal getAcctYesterdayBalance() {
        return acctYesterdayBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_info.acct_yesterday_balance
     *
     * @param acctYesterdayBalance the value for acct_info.acct_yesterday_balance
     *
     * @mbg.generated
     */
    public void setAcctYesterdayBalance(BigDecimal acctYesterdayBalance) {
        this.acctYesterdayBalance = acctYesterdayBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_info.acct_today_balance
     *
     * @return the value of acct_info.acct_today_balance
     *
     * @mbg.generated
     */
    public BigDecimal getAcctTodayBalance() {
        return acctTodayBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_info.acct_today_balance
     *
     * @param acctTodayBalance the value for acct_info.acct_today_balance
     *
     * @mbg.generated
     */
    public void setAcctTodayBalance(BigDecimal acctTodayBalance) {
        this.acctTodayBalance = acctTodayBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_info.data_create_user
     *
     * @return the value of acct_info.data_create_user
     *
     * @mbg.generated
     */
    public String getDataCreateUser() {
        return dataCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_info.data_create_user
     *
     * @param dataCreateUser the value for acct_info.data_create_user
     *
     * @mbg.generated
     */
    public void setDataCreateUser(String dataCreateUser) {
        this.dataCreateUser = dataCreateUser == null ? null : dataCreateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_info.data_create_time
     *
     * @return the value of acct_info.data_create_time
     *
     * @mbg.generated
     */
    public String getDataCreateTime() {
        return dataCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_info.data_create_time
     *
     * @param dataCreateTime the value for acct_info.data_create_time
     *
     * @mbg.generated
     */
    public void setDataCreateTime(String dataCreateTime) {
        this.dataCreateTime = dataCreateTime == null ? null : dataCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_info.data_update_user
     *
     * @return the value of acct_info.data_update_user
     *
     * @mbg.generated
     */
    public String getDataUpdateUser() {
        return dataUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_info.data_update_user
     *
     * @param dataUpdateUser the value for acct_info.data_update_user
     *
     * @mbg.generated
     */
    public void setDataUpdateUser(String dataUpdateUser) {
        this.dataUpdateUser = dataUpdateUser == null ? null : dataUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_info.data_update_time
     *
     * @return the value of acct_info.data_update_time
     *
     * @mbg.generated
     */
    public String getDataUpdateTime() {
        return dataUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_info.data_update_time
     *
     * @param dataUpdateTime the value for acct_info.data_update_time
     *
     * @mbg.generated
     */
    public void setDataUpdateTime(String dataUpdateTime) {
        this.dataUpdateTime = dataUpdateTime == null ? null : dataUpdateTime.trim();
    }
}